/**
 * gridbox schema 嘅 Postgres DDL（idempotent，可以重複執行）。
 * - server 開機時由 bootstrap 自動執行
 * - 同一份 SQL 亦可以直接貼入 Supabase SQL Editor 執行（見 db/migrations/0001_gridbox.sql）
 * 欄位名係 camelCase，所以要加雙引號。
 * RLS 開啟但冇 policy：Supabase 嘅 anon / authenticated 角色一律讀唔到；
 * 本 app 用 DATABASE_URL（postgres 角色）直連，唔受 RLS 影響。
 */
export const DDL: string[] = [
  `CREATE SCHEMA IF NOT EXISTS gridbox`,
  `CREATE TABLE IF NOT EXISTS gridbox.users (
    id serial PRIMARY KEY,
    "unionId" text NOT NULL UNIQUE,
    name text,
    email text,
    avatar text,
    "passwordHash" text,
    role text NOT NULL DEFAULT 'user' CHECK (role IN ('user','staff','admin')),
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "lastSignInAt" timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS gridbox.tenants (
    id serial PRIMARY KEY,
    "userId" integer REFERENCES gridbox.users(id) ON DELETE SET NULL,
    name text NOT NULL,
    phone text,
    email text,
    note text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now()
  )`,
  // 銷售分析開通（舊資料庫補欄；預設關閉，要店主批准）
  `ALTER TABLE gridbox.tenants ADD COLUMN IF NOT EXISTS "analyticsEnabled" boolean NOT NULL DEFAULT false`,
  `ALTER TABLE gridbox.tenants ADD COLUMN IF NOT EXISTS "analyticsApprovedAt" timestamptz`,
  `ALTER TABLE gridbox.tenants ADD COLUMN IF NOT EXISTS "analyticsApprovedBy" integer REFERENCES gridbox.users(id) ON DELETE SET NULL`,
  `CREATE TABLE IF NOT EXISTS gridbox.grids (
    id serial PRIMARY KEY,
    code text NOT NULL UNIQUE,
    size text NOT NULL DEFAULT 'M' CHECK (size IN ('M','L')),
    "monthlyRent" numeric(12,2) NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'vacant' CHECK (status IN ('vacant','occupied','reserved')),
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS grids_status_idx ON gridbox.grids (status)`,
  `CREATE TABLE IF NOT EXISTS gridbox.leases (
    id serial PRIMARY KEY,
    "gridId" integer NOT NULL REFERENCES gridbox.grids(id),
    "tenantId" integer NOT NULL REFERENCES gridbox.tenants(id),
    "startDate" text NOT NULL,
    "endDate" text NOT NULL,
    "rentFreeDays" integer NOT NULL DEFAULT 0,
    "monthlyRent" numeric(12,2) NOT NULL,
    deposit numeric(12,2) NOT NULL,
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','ended')),
    note text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS leases_grid_idx ON gridbox.leases ("gridId")`,
  `CREATE INDEX IF NOT EXISTS leases_tenant_idx ON gridbox.leases ("tenantId")`,
  `CREATE TABLE IF NOT EXISTS gridbox.sales (
    id serial PRIMARY KEY,
    "gridId" integer REFERENCES gridbox.grids(id),
    "tenantId" integer REFERENCES gridbox.tenants(id),
    "saleDate" text NOT NULL,
    "saleTime" text,
    "productName" text NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    "unitPrice" numeric(12,2) NOT NULL,
    "totalAmount" numeric(12,2) NOT NULL,
    note text,
    "createdBy" integer REFERENCES gridbox.users(id) ON DELETE SET NULL,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS sales_date_idx ON gridbox.sales ("saleDate")`,
  `CREATE INDEX IF NOT EXISTS sales_grid_idx ON gridbox.sales ("gridId")`,
  `CREATE INDEX IF NOT EXISTS sales_tenant_idx ON gridbox.sales ("tenantId")`,
  `CREATE TABLE IF NOT EXISTS gridbox.rent_records (
    id serial PRIMARY KEY,
    "leaseId" integer NOT NULL REFERENCES gridbox.leases(id),
    "gridId" integer NOT NULL REFERENCES gridbox.grids(id),
    "tenantId" integer NOT NULL REFERENCES gridbox.tenants(id),
    month text NOT NULL,
    type text NOT NULL CHECK (type IN ('rent','deposit')),
    amount numeric(12,2) NOT NULL,
    status text NOT NULL DEFAULT 'unpaid' CHECK (status IN ('unpaid','paid')),
    "paidAt" text,
    note text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS rent_month_idx ON gridbox.rent_records (month)`,
  `CREATE INDEX IF NOT EXISTS rent_lease_idx ON gridbox.rent_records ("leaseId")`,
  `CREATE TABLE IF NOT EXISTS gridbox.employees (
    id serial PRIMARY KEY,
    name text NOT NULL,
    phone text,
    "hourlyRate" numeric(12,2) NOT NULL CHECK ("hourlyRate" >= 0),
    "mpfEnrolled" boolean NOT NULL DEFAULT true,
    active boolean NOT NULL DEFAULT true,
    note text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS gridbox.shifts (
    id serial PRIMARY KEY,
    "employeeId" integer NOT NULL REFERENCES gridbox.employees(id),
    "workDate" text NOT NULL,
    "startTime" text NOT NULL,
    "endTime" text NOT NULL,
    "breakMinutes" integer NOT NULL DEFAULT 0 CHECK ("breakMinutes" >= 0),
    "hourlyRate" numeric(12,2) NOT NULL CHECK ("hourlyRate" >= 0),
    note text,
    "createdBy" integer REFERENCES gridbox.users(id) ON DELETE SET NULL,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS shifts_emp_date_idx ON gridbox.shifts ("employeeId", "workDate")`,
  `CREATE TABLE IF NOT EXISTS gridbox.payroll_payments (
    id serial PRIMARY KEY,
    "employeeId" integer NOT NULL REFERENCES gridbox.employees(id),
    month text NOT NULL,
    hours numeric(8,2) NOT NULL,
    "basePay" numeric(12,2) NOT NULL,
    adjustment numeric(12,2) NOT NULL DEFAULT 0,
    "grossPay" numeric(12,2) NOT NULL,
    "mpfEmployee" numeric(12,2) NOT NULL,
    "mpfEmployer" numeric(12,2) NOT NULL,
    "netPay" numeric(12,2) NOT NULL,
    "paidAt" text NOT NULL,
    note text,
    "createdAt" timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS payroll_emp_month_uq ON gridbox.payroll_payments ("employeeId", month)`,
  // 考勤機匯入（工號對應員工；每人每月一條）；強積金已停用 → 舊欄預設 0
  `ALTER TABLE gridbox.employees ADD COLUMN IF NOT EXISTS "staffCode" text`,
  `CREATE UNIQUE INDEX IF NOT EXISTS employees_staff_code_uq ON gridbox.employees ("staffCode") WHERE "staffCode" IS NOT NULL`,
  `ALTER TABLE gridbox.payroll_payments ALTER COLUMN "mpfEmployee" SET DEFAULT 0`,
  `ALTER TABLE gridbox.payroll_payments ALTER COLUMN "mpfEmployer" SET DEFAULT 0`,
  `CREATE TABLE IF NOT EXISTS gridbox.attendance (
    id serial PRIMARY KEY,
    "employeeId" integer NOT NULL REFERENCES gridbox.employees(id),
    month text NOT NULL,
    "shiftCount" integer NOT NULL DEFAULT 0 CHECK ("shiftCount" >= 0),
    seconds integer NOT NULL CHECK (seconds >= 0),
    hours numeric(8,2) NOT NULL,
    "hourlyRate" numeric(12,2) NOT NULL CHECK ("hourlyRate" >= 0),
    period text,
    "createdBy" integer REFERENCES gridbox.users(id) ON DELETE SET NULL,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS attendance_emp_month_uq ON gridbox.attendance ("employeeId", month)`,
  `ALTER TABLE gridbox.users ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE gridbox.tenants ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE gridbox.grids ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE gridbox.leases ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE gridbox.sales ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE gridbox.rent_records ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE gridbox.employees ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE gridbox.shifts ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE gridbox.payroll_payments ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE gridbox.attendance ENABLE ROW LEVEL SECURITY`,
];
